### ISSUE TITLE
When threading, all individuals get same results.

### ISSUE THREAD

**Issue by MrMatsson** [fangzhou-xie/rethnicity#3]
Works perfectly when I run only one name at the time.
But when I tried the recommended code for running multiple names at the same time from "https://fangzhou-xie.github.io/rethnicity/articles/introduction.html" .

I get identical results for all individuals.
Thank you for your potential future assistance. 

![image](https://user-images.githubusercontent.com/100193952/156366245-c9994b90-f9b7-4dcf-869f-dd9d49f52d1e.png)
![image](https://user-images.githubusercontent.com/100193952/156366305-5d8646fa-31df-44d5-b011-11e1d630070b.png)

**Comment by fangzhou-xie** [comment]
Your question has been answered #2. Please do not open new issue when you have the same question. 

As I have explained in #2, this has nothing to do with threading. **dataframe** and **vector** are different objects in R.
