### ISSUE TITLE
issue with installation "C++14 standard requested but CXX14 is not defined"

### ISSUE THREAD

**Issue by Lukaku92** [fangzhou-xie/rethnicity#5]
I have problems with the installation.

First I get this message:

Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘rethnicity’

Then, I am asked to confirm whether I want to download from sources, and I give permission.

This is the message that I get when finally the package is being installed:

* installing *source* package 'rethnicity' ...
** package 'rethnicity' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined
* removing 'C:/Users/luca_/Documents/R/win-library/3.6/rethnicity'
Warning in install.packages :
  installation of package ‘rethnicity’ had non-zero exit status

So, eventually, the package is not installed.

What should I do?

**Comment by fangzhou-xie** [comment]
It seems to me that you are: (1) on Windows, (2) using R 3.6. And the error seems to compiler issue.

I would suggest you to update your R first to see if this helps. The most recent is R [4.1.3](https://cran.r-project.org/bin/windows/base/).

**Comment by Lukaku92** [comment]
@fangzhou-xie 
Thank you! this is great, now it is installed

**Comment by fangzhou-xie** [comment]
Great! Glad to help. Closing the issue now.
